"""add species label project id

Revision ID: 504cfd509f5f
Revises: 4cf2f0d88592
Create Date: 2025-11-04 15:50:37.777912

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "504cfd509f5f"
down_revision: Union[str, Sequence[str], None] = "4cf2f0d88592"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "labelstudioproject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label_studio_project_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_labelstudioproject_label_studio_project_id"),
        "labelstudioproject",
        ["label_studio_project_id"],
        unique=True,
    )
    op.create_table(
        "labelstudioprojectdivemapping",
        sa.Column("label_studio_project_id", sa.Integer(), nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dive_id"],
            ["dive.id"],
        ),
        sa.ForeignKeyConstraint(
            ["label_studio_project_id"],
            ["labelstudioproject.id"],
        ),
        sa.PrimaryKeyConstraint("label_studio_project_id", "dive_id"),
    )
    op.add_column(
        "dive", sa.Column("species_label_project_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "dive", "labelstudioproject", ["species_label_project_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dive", type_="foreignkey")
    op.drop_column("dive", "species_label_project_id")
    op.drop_table("labelstudioprojectdivemapping")
    op.drop_index(
        op.f("ix_labelstudioproject_label_studio_project_id"),
        table_name="labelstudioproject",
    )
    op.drop_table("labelstudioproject")
    # ### end Alembic commands ###
